### ISSUE TITLE
Update response limit error messages

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#1343]
When the response limit is reached, Storage mode shows submission error with no good recovery text, while Email mode shows the correct error message. Update Storage mode error message to Email mode message.

**Comment by jia1** [comment]
@syan-syan is this issue fixed by the team already? When I pull the `develop` branch, I get these messages when I hit submission limit for email mode and storage mode respectively.

Email mode:
![Screenshot 2021-07-06 at 7 15 44 PM](https://user-images.githubusercontent.com/14961285/124591371-cd899400-de8e-11eb-8b4f-01084f638517.png)

Storage mode:
![Screenshot 2021-07-06 at 7 14 49 PM](https://user-images.githubusercontent.com/14961285/124591404-d712fc00-de8e-11eb-9331-408e598d5580.png)

**Comment by jia1** [comment]
Update: It's the error when the submission limit hits before the user submits (so form is already closed when submitting)
