### ISSUE TITLE
Add response ID to thank you page and email confirmation

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#1409]
problem
- respondents dont have their submission Id unless admin attaches PDF to email confirmation
- this gets in the way of communicating with agency about their response in future 

todo: 
- add responseid to thank you page and email confirmation as in design below

design: https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1166%3A246

------
PREVIOUS:

todo [design]
- competitive research on what other form managers refer to this as. this is backwards incompatible as it has to match what the admins refer to it as, and RPA on both admin and respondent emails might break if we change this around frivolously.
- ID vs reference number?
- response vs submission?

suggested design
- include "Response reference number: ###########" before the rest of email body in unformatted text
- show this but in a different colour in the preview box on admin panel. can use an obviously fake number like 123456789.

**Comment by pearlyong** [comment]
Research on other form managers [here](https://docs.google.com/document/d/1imkU7aumlPNwoHEjc2s919u7xEoMQ2XYTsmohGq-g4Q/edit?usp=sharing)
[Figma](https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1166%3A246) on incorporating ID into Thank You page

**Conclusion:**
- The term ‘ID’ is widely used, we should continue to use that
- Since we are using Response consistently, we should keep that and change the unique reference to Response ID

**Suggested design:**
- Agree with both your points (except that we should use Response ID). For preview in admin panel, 'Response ID: 123456789' can be in #979797

**Comment by pearlyong** [comment]
For preview in admin panel, can use this [design](https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1439%3A100)

**Comment by syan-syan** [comment]
@chowyiyin btw the actual email confirmation should also have a divider line after response ID, just like the preview, responsive to width.
