### ISSUE TITLE
[API] Migrate GET submission metadata related endpoints to /api counterpart

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#1520]
This issue tracks the migration of `GET /:formId/adminform/submissions/` and `GET /:formId/adminform/submissions/metadata` to their new `/api` counterparts.

This issue is distinct from #1511 due to the request query parameter shifting into the endpoint itself, which requires a new controller to be written instead of just duplicating the route. 
This change is proposed as the current endpoints are not RESTful, as queries should be for properties of a resource, not the identifier for a resource.

\# | Existing endpoints | New endpoints<br>(note that all routes are prefixed with /api/v3) | Description
-- | -- | --|--|
1 | GET /:formId/adminform/submissions/<br>{ query: { submissionId } } | GET /admin/forms/:formId/submissions/:id | Retrieve submission by id
2 | GET /:formId/adminform/submissions/metadata<br>{ query: { submissionId, page } } | GET /admin/forms/:formId/submissions/metadata<br>{ query: { searchId?, page = 1 } } | Search by submission

> For the first endpoint, note the inlining of `query.submissionId` to the resource identifier `:id` in the endpoint itself.

The second endpoint just has a change in query params from `submissionId` to `searchId` for better clarity as to what the query is used for

**Comment by seaerchin** [comment]
@karrui i will name the new controller `handleGetEncryptedResponseWithUrlParams` just to be clear. this is because we can't delete the old one so the distinction should be made explicit ;--;

**Comment by seaerchin** [comment]
as discussed, for the second point, will only migrate the `routes` but not the actual `controller` for 2 reasons: 

1. FE is now doing a search on an exact match rather than a substring search so the renaming might not be very applicable 
2. Code duplication on controller might not be worth the trouble

**Comment by seaerchin** [comment]
@karrui could i get some clarification on the intent behind the page number defaulting to 1? Currently, the validator ensures that page number is set only when `submissionId` is not present. however, this leads to a case where users might have a less than pleasant experience because they will hit a 400 error then they do not specify both submissionId and page number. 

Hence, if the intention behind the parameter is to be more permissive to the users, should we delete the validation altogether and set a default parameter on the pageNumber instead?

**Comment by seaerchin** [comment]
clarified the above issue - validation is still needed to ensure the existence of at least one of the two parameters and to prevent additional parameters from being queried by the client
