### ISSUE TITLE
server should also validate esrvcId is valid when updating form esrvcId settings

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#1708]
the `PATCH /forms/:formId/settings` controller handler should validate esrvcId validity in addition to the client (either when setting the esrvcId value, or changing the form from private to public), and should not solely rely on frontend checks

**Comment by syan-syan** [comment]
assuming we are checking the same way, I think this might be unnecessary because our check is mainly put in for user experience reasons - we don't want the form admin to think they have a working live Singpass form that doesn't actually work. the real guarantee has always been that SP will return an error on invalid esid. 

it's quite unlikely someone will try to circumvent this and if they do, we're not responsible for that user experience and they should expect it when SP errors on the invalid esid.

**Comment by syan-syan** [comment]
#wontfix for now
