### ISSUE TITLE
Convert form-api.client.factory.js to TypeScript

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1835]

**Comment by mantariksh** [comment]
This factory contains a couple of parts in terms of functionality:
(1) API calls to various endpoints
(2) Interceptors which perform various transformations on the requests and responses

(2) is coupled to `form-fields.client.factory`, so it will be difficult to migrate. Hence a possible approach could be to migrate (1) by creating TypeScript services to replace the `$resource` object, but preserve `form-api.client.factory` in order to keep the functionality of (2).

**Comment by mantariksh** [comment]
Can also take the opportunity to tackle #1768
