### ISSUE TITLE
Issue running locally

### ISSUE THREAD

**Issue by fabiodouek** [opengovsg/FormSG#3445]
**Describe the bug**
I'm trying to evaluate the solution and followed the steps to run locally: "npm run dev"

However, I'm getting a blank page and 404 for the http://localhost:5000/public/bundle.js

**To Reproduce**
1. Run "npm run dev" (as described in the doc)
2. Access from the browser http://localhost:5000
3. As a result, I get a blank page and 404 for the http://localhost:5000/public/bundle.js

**Expected behavior**
I would expect to be able to access the FormSG app

**Desktop (please complete the following information):**
 - OS: MacOS 12.2
 - Browser: Chrome
 - Version: 97.0.4692.99

**Comment by mantariksh** [comment]
hi @fabiodouek, webpack just takes a really long time to bundle the AngularJS frontend. if you wait for around 5-10 more minutes, you should see the webpack output in the console and should be able to access the app at localhost:5000.

we understand that this is awfully, awfully slow, which is why we are spending most of our time on the frontend React migration, which you can check out on the branch called `form-v2/develop`.

let us know if it works!

**Comment by fabiodouek** [comment]
Thanks for the quick reply @mantariksh . Unfortunately it didn't work. Not sure if that could be am issue with the watch options with MacOS. Is there a docker-compose file with production settings so I can do a webpack prod build into the docker container?

**Comment by fabiodouek** [comment]
Hi @mantariksh , perfect thanks a lot. It's working now

**Comment by mantariksh** [comment]
@fabiodouek great! if it's not too much trouble, could you drop me an email at antariksh@open.gov.sg? it'd be great to find out more about your use case
