### ISSUE TITLE
Put user last login key in db

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#345]
allows us to track monthly active users and identify inactive accounts

**Comment by karrui** [comment]
@syan-syan 

A few more clarifications: do we update only on login, or whenever the `/user` endpoint is accessed?

On login will not be as accurate, since the session cookie expires only after 24 hours, but this means we don't update the DB as often. I assume that is not too bad of a tradeoff and will be implementing the update of the database only on login.

**Comment by syan-syan** [comment]
as discussed 24h accuracy is fresh enough for our purposes (understanding which users are active)
