### ISSUE TITLE
Explore alternate hashing mechanism for OTPs and MyInfo

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3968]
We currently use the `bcrypt` library for hashing OTPs. This hashing is highly CPU-intensive, so server CPU utilisation spikes when  there are many users requesting for OTPs for verified mobile/email fields.

We should switch to a different hashing mechanism which is less CPU-intensive, and apply this throughout the app where `bcrypt` isn't necessary. Non-exhaustive list of features where this can be applied:
- Admin login OTPs
- Verified field OTPs
- MyInfo verification hashes

This needs to be done in a backwards-compatible manner, i.e. existing hashes in the DB should still be valid. One way to do this could be to check for the hash prefix, as [`bcrypt` hashes always start with `$2$`](https://auth0.com/blog/hashing-in-action-understanding-bcrypt/).

**Comment by wanlingt** [comment]
@timotheeg 's comments:

On the encryption topic, the brute force concern is coupled to a malicious user having access to the DB, or having breached the servers and executing code from them. Otherwise the rate limit on REST API endpoints + CF WAF should prevent REST based BF.

From that, my thinking is that we do not need cryptographically secure hashing for OTPs, so I’d rather be as light as possible, as long as we should not have a plain, buffet-style, read-and-get-usable-value system (meaning both clear text and straight hashes are no-go) that looks negligent.

Long-ish salt + fast hashing sounds good enough to me. And for “fast hashing”, even sha2 is probably too expensive. We could use [xxhash](https://github.com/Cyan4973/xxHash) instead.

**Comment by LinHuiqing** [comment]
Migrated to Linear: FRM-1382
