### ISSUE TITLE
a11y: all icons used in forms are being labeled as "image"

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4183]
We should either hide the icons from screen readers using aria-hidden or add clearer labels to the icons used.

e.g.
yes/no field checkmark/cross icons
rating field star icons

**Comment by justynoh** [comment]
actually, it seems that being labelled as "image" is correct: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA24

> The key is for the author to semantically markup icon fonts with `role="img"`.

there is also no role for icons: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles

I think it's sufficient to add aria-labels that suffix in "icon", so that it reads "Rating star icon, image" or something like that
