### ISSUE TITLE
Top navigation gets cut off after moving fields around

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4307]
Ask @pearlyong or @mantariksh to replicate (not sure how to do so reliably yet)
<img width="1105" alt="Screenshot 2022-07-25 at 7 04 17 PM" src="https://user-images.githubusercontent.com/29480346/180763190-b164a8db-6c17-4488-a5a8-363e8ed952df.png">

**Comment by justynoh** [comment]
To reliably replicate the issue, instead of dragging and dropping fields from the builder drawer into the builder, just click a field in the builder (which adds it to the end of the form). This will cause the top nav to get cut off.

https://user-images.githubusercontent.com/25571626/181408089-3195aee4-1950-4776-bca6-e1e9ff12963a.mov

**Comment by karrui** [comment]
this should be fixed by #4451
