### ISSUE TITLE
Enable changing of MyInfo e-service IDs even with MyInfo fields

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4540]
Currently, MyInfo form admins go through a pretty painful process if they forget to enter their e-service IDs. First, create a new form with MyInfo enabled. Don't add an e-service ID.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/25571626/183841642-54169a54-e690-404d-81e4-c74a8a48637a.png">

Now create a MyInfo field. Let's say i created a bunch of fields and I'm ready to enable my form. I'm prompted to add an e-service ID before opening the form.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/25571626/183844512-77244bb0-78be-4567-81fe-ed46496c092c.png">

But when i go and try to change it, I need to remove all my fields to change the e-service ID!

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/25571626/183841775-bfc81762-e7ea-4ad2-83dc-28bbaae99b15.png">

**Comment by justynoh** [comment]
Ideally, the e-service ID box should only be disabled once the form is open.

**Comment by mantariksh** [comment]
actually historically the e-service ID box was disabled when the form is open because we validated the e-service ID at the point of opening the form. but we don't do this validation anymore. so actually we can leave the text input enabled at all times, even when the form is open.

but we should maintain the condition that all MyInfo fields must be removed before the auth method can be changed from something other than MyInfo.
