### ISSUE TITLE
[1] Leading 0s in decimal field are not validated in the frontend

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4640]
**Describe the bug**
Error for leading 0s only shows up when user tries to submit the form. This should be displayed as a frontend validation message similar to MIN and MAX, e.g. 
<img width="783" alt="image" src="https://user-images.githubusercontent.com/56983748/185887825-d31f5b05-3693-4af8-9af6-97ae75a16590.png">

Current state:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/56983748/185887670-a84c22cc-2573-466c-a91d-440461adc43e.png">

**Comment by mantariksh** [comment]
@pearlyong 
"Answer cannot start with 0"
(feel that the term "Leading 0" is not the most understandable)

**Comment by karrui** [comment]
> "Answer cannot start with 0"

@mantariksh but hor this is a decimal field, answers can absolutely start with 0 (e.g. 0.1, 0.000005, etc)

**Comment by karrui** [comment]
should I just add a transformation step to convert it to numbers? i.e 
```tsx
const nextValue = String(Number(currValue))
```

**Comment by mantariksh** [comment]
@karrui you're totally right, and I realise that in current production we even allow like 0005.5. but then the bug which @wanlingt encountered is due to something else. can try to replicate?

**Comment by karrui** [comment]
@mantariksh AngularJS strips leading zeros on the client before submission. The error is indeed because of leading zeroes. I think for React I'll add a validation instead so users' inputs are not changed 

edit: updating error message to be 'Please enter a valid decimal without leading zeros' until pearly thinks of something better, haha
