### ISSUE TITLE
[2] Table field requires double clicks to add more rows

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4753]
To replicate:
1. Enable "Add more rows"
2. Reduce minimum number of rows
3. Now "Add more rows" toggle needs two clicks to toggle

**Comment by tohhengxing** [comment]
this problem is actually a bit more complicated. It happens as long as there is highlighted text anywhere on the page for every chakra checkbox.

Why it happens when you reduce minimum rows is because it highlights the text inside the input field, thus triggering the above.

It doesn't seem very straightforward to resolve currently.

However, it has recently  been fixed.

https://github.com/chakra-ui/chakra-ui/issues/4216
https://github.com/chakra-ui/chakra-ui/pull/6194
