### ISSUE TITLE
Country field

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#481]
basically a dropdown with country list filled in.

useful for
- citizenship / nationality
- place of birth
- component of address field

**Comment by aniruddha-adhikary** [comment]
#### Idea: Generic Datasets for Selection Fields

Instead of creating different types of fields for Countries, could we consider having "datasets"? Essentially, there could be pre-filled templates users could select,

1. Nationalities
2. Countries
3. Types of Travel Documents
4. Timezones
etc.

Selecting one of these "templates" would fill the options with appropriate values. So, in the editor, a dropdown menu for selecting an optional template as a "shortcut" for common dropdowns.
