### ISSUE TITLE
Clearer copy for field verification error

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4887]
![image](https://user-images.githubusercontent.com/29480346/190559279-757e6bcd-d675-4dcd-ba73-61d71b60fa53.png)

The long-term fix for this is #4618, but in the meantime, the copy can be improved to make the required action clearer to the user.
"Verify your mobile number below."
"Verify your email address below."

**Comment by mantariksh** [comment]
assigning @pearlyong for thoughts on copy

**Comment by pearlyong** [comment]
the copy is ok for a quick fix

**Comment by wanlingt** [comment]
<img width="1195" alt="Screenshot 2022-09-19 at 6 57 12 PM" src="https://user-images.githubusercontent.com/56983748/191002957-5ea07c33-8c9e-4812-a5d6-fc8e089ef066.png">

can I confirm that this is what the copy should look like? it looks a bit strange before the user clicks on Verify

**Comment by pearlyong** [comment]
the ideal behaviour should be [#4618](https://github.com/opengovsg/FormSG/issues/4618) : 
- user enters email
- user clicks on Verify button
- OTP content block is displayed to user
- no error message is displayed to user (unless they typed in an invalid email)

interim fix could be
- user enters email
- user clicks on Verify button
- inline error is displayed (verify your email address below)
- at the same time, OTP content block is displayed to user

@mantariksh was this what you were thinking of too?

**Comment by wanlingt** [comment]
@pearlyong to clarify what the desired **ideal behaviour** in more detail:
scenario 1 - user clicks on Verify button immediately after entering email
- user enters email
  - if email is not valid, an error will appear
- user clicks on Verify button
- OTP content block is displayed to user
- no error message is displayed to user (unless they typed in an invalid email)

scenario 2 - user clicks away immediately after entering email
- user enters email
  - if email is not valid, an error will appear
- user clicks away (e.g. to the next field) without clicking the Verify button
- error message appears, indicating field verification is required
- user clicks on Verify button, no error message is displayed to user (? not sure)
- OTP content block is displayed to user

Re the **interim fix**, I think we're not looking to change **when** the inline error is displayed (since that's a harder fix that we will solve in #4618), only the inline error message. So the flow should be the same.
- user enters email
- if user clicks away (to another field, or the Verify button) the error appears
- error disappears when the field is verified

Screen recording of current behaviour for clarity:
https://user-images.githubusercontent.com/56983748/191233892-a7b74fb5-b6a5-447b-8627-001064135f65.mov




Maybe we can change the message to "Please verify your email/mobile"?

**Comment by pearlyong** [comment]
for interim fix, yes you're right! and let's use anti's copy 
"Verify your mobile number below"
"Verify your email address below"

for the ideal, let me chat with anti and get back. the idea is that we shouldn't be showing users an error message if they did not make a mistake, but also understand it's a real required field error

**Comment by pearlyong** [comment]
for interim fix, yes you're right! and yea it looks strange before clicking on Verify, we can stick with your proposed copy. @mantariksh ok?

Please verify your email
Please verify your mobile

will get back on the ideal

**Comment by wanlingt** [comment]
@pearlyong i asked @mantariksh , yes he's ok with the copy. he says to refine it slightly to 
Please verify your email address
Please verify your mobile number

will go ahead with this, thanks both!
