### ISSUE TITLE
storage mode view submissions - search / filter elements

### ISSUE THREAD

**Issue by tshuli** [opengovsg/FormSG#489]
Currently, there are too many elements for search / filter on the storage mode view submissions page in a single row. This results in the elements overflowing the page when screen width is between 768px - 1200px.

![Screenshot from 2020-10-19 20-01-50](https://user-images.githubusercontent.com/63710093/96451299-f0fda780-1249-11eb-9c41-e502eeaa0bf6.png)

**Comment by shuli-ogp** [comment]
@syan-syan may be useful for design to take a quick look on how the elements can be arranged

**Comment by syan-syan** [comment]
tagged @pearlyong

**Comment by pearlyong** [comment]
zeplin screens here: https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/dashboard?seid=5f2b71d865bd2a2798438461

For smaller screen sizes, the elements should be stacked.
Due to constraint of space on mobile, when search bar expands, it can cover the number of responses. (same pattern as Billing)

**Comment by syan-syan** [comment]
wont fix as minor issue and migrating to react
