### ISSUE TITLE
Stealth textfield prefill feature from query parameters

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#498]
If a query parameter is provided to a form URL in one of the following formats:

Server-side URL
- `https://form.gov.sg/<formId>?<fieldId1>=<value1>&<fieldId2>=<value2>...`

Client-side URL (server can't see anything after hashbang)
- `https://form.gov.sg/#!/<formId>?<fieldId1>=<value1>&<fieldId2>=<value2>...`

and if the `fieldIds` are valid mongoose object IDs and refer to a short text field, then prefill and disable editing the corresponding form field on the frontend.

Path and query parameters can be retrieved with the AngularJS [$location](https://docs.angularjs.org/guide/$location) service. Watch for edge cases depending on whether the [hashbang or query parameters come first](https://github.com/angular/angular.js/issues/6172).

**Comment by shuli-ogp** [comment]
For discussion on whether to expand prefill to support the following use cases

Singpass forms; currently the query params are lost on singpass redirect
Non-english characters; currently not supported due to sanitizing input
Other field types. Although short text field already accepts string (i.e. can input any value), expanding to other field types will allow you to apply more types of custom validation (e.g. number validation). Note that short text custom validation already works with prefill
