### ISSUE TITLE
Make the individual field more distinguishable in builder preview

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5426]
Fields demarkation is not clear espacially for greyed out fields in complex logic. This makes it harder for users to figure out which field they should edit or add/remove from the logic. We can again call the user who has reported this issue.

From screenshots it's clear that this is a change from our angular behaviour and might be bothering some other users.

React:

![Image](https://user-images.githubusercontent.com/107169604/202915106-8e903ae1-8910-4af3-8aba-0bac7a507d94.png)

Angular:

![Image](https://user-images.githubusercontent.com/107169604/202915129-54dcd49d-6604-40be-b2d5-786a66dc5915.png)

**Comment by amitogp** [comment]
@staceytan1998 Can we make fields more distinguishable without adding demarcation markers?

**Comment by staceytan1998** [comment]
We already have hover states for fields, that is a way of making them distinguishable without adding markers as a default state. Also the form preview should look like the actual form as much as possible. 

Previously we decided to deprioritise this because to add/remove logic, it is done in the logic tab not the builder. At the same time we also found the bug where statement data doesn't show in logic builder, this could have been the reason why the user found it hard to add/remove! 

Is there any other concerns regarding this that design is not aware of? 😅
