### ISSUE TITLE
double check all ng-trim on angularJS and check that it corresponds to a trim on React

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5655]
we've had multiple bugs related to inconsistencies with whitespace behaviour in AngularJS vs React

**Comment by justynoh** [comment]
from a cursory search, occurrences of ng-trim in angular:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/25571626/209920147-ae2124aa-8e66-4503-a3de-6e93ead0be0f.png">


place | `ng-trim` in angular | frontend trim in react?
------|---------------------|--------------
Checkbox "Others" field | ✅  | ❌ 
Email | ✅  | ❌ (2)
NRIC | ✅  | ✅  (1)
Number | ✅  | ✅  (2)
Radio "Others" field | ✅  | ❌ 
Long text | ✅  | ✅ 
Short text | ✅  | ✅ 
UEN | ✅  | ✅  (1)
Decimal | ❌ | ✅  (2)
feedback form on endpage | ❌ | ❌ (3)

For those numbered, the trimming does not affect the result because
(1) inputs with leading/trailing whitespaces are considered invalid NRIC/UEN, so respondents need to self-trim anyway
(2) we completely disallow spaces in these fields, i.e. when a respondent enters a "space" nothing actually happens to the input (this should be the desired behavior for the other fields as well, actually)
(3) we perform model-level trimming, so what we do to the content on the frontend actually doesn't matter

**Comment by justynoh** [comment]
As a next step i think we should just do two things.

1) trim others inputs for checkboxes and radio in `inputTransformation.ts`
2) modify NRIC/UEN fields so that spaces in those fields are automatically removed onChange, i.e. a form filler doesn't see anything when they click space.

Thoughts?

**Comment by wanlingt** [comment]
> As a next step i think we should just do two things.
> 
> 1. trim others inputs for checkboxes and radio in `inputTransformation.ts`
> 2. modify NRIC/UEN fields so that spaces in those fields are automatically removed onChange, i.e. a form filler doesn't see anything when they click space.
> 
> Thoughts?

thanks for documenting that! the 2 approaches make sense to me. would add on 3. check backend validation behaviour and make sure it's consistent with both frontends

**Comment by LoneRifle** [comment]
We've removed AngularJS for a while now, so assuming that this no longer applies
