### ISSUE TITLE
NRIC field does not auto correct leading/trailing whitespaces 

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5854]
**Describe the bug**
Another regression in the React App (works in Angular) - if the form filler inputs an NRIC with whitespaces into the NRIC field, they are unable to submit their form

**Expected behavior**
NRIC field should auto trim leading/trailing whitespaces

**Additional Context**
Also mentioned in https://github.com/opengovsg/FormSG/issues/5655#issuecomment-1367152964

**Comment by timotheeg** [comment]
Feedback from user on the issue after frustrations in submitting a form:

> On 15 February, I log in at 9am sharp and proceeded to fill up the form. However when I wanted to submit the form, I was notified that my NRIC number is wrong which isn’t. So I used my common sense to delete and retyped. It took 2 attempts to remove the “NRIC is inaccurate” notice.

**Comment by KenLSM** [comment]
The issue is related to the migration of Angular -> React where angular had auto-trimmed [toggled on](https://github.com/opengovsg/FormSG/blob/v6.32.0/src/public/modules/forms/base/componentViews/field-nric.client.view.html#L36).

Further digging of related issues, I've also found that `UENField` might also face such an issue. Created #5867 to track this.
