### ISSUE TITLE
Strengthen UEN verification

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#5919]
**Is your feature request related to a problem? Please describe.**
To strengthen our UEN verification.

We are currently checking the UEN format through [ACRA](https://www.uen.gov.sg/ueninternet/faces/pages/admin/aboutUEN.jspx), however, we do not ensure if the UEN number is valid. Even though the we do not have the formula for checksum generation, we can reverse engineer it through the vast amount of dataset that's available on [data.gov.sg](https://data.gov.sg/dataset/entities-with-unique-entity-number).

**Describe the solution you'd like**
We chanced upon the open sourced [arthurdejong/python-stdnum](https://github.com/arthurdejong/python-stdnum) project that collected a whole bunch of standard formats, and included the checksum algorithm for UEN. We would want to verify the checksum against the dataset, and subsequently include the checksum algorithm into our validator.

**Comment by packirisamykaran** [comment]
Hi, I would like to contribute to this project. Guide me on how I can help fix this issue

**Comment by hui-jie-lim** [comment]
hi @KenLSM , i think i can pick this up if no ones working on this yet. Will need some help navigating like if there are existing checksums and where I can find them. I can have a look at the package and verify it first before working on the integration

**Comment by KenLSM** [comment]
Hey @hui-jie-lim, we don't have anyone working on this in the moment. 

From our initial research, the checksum library provided by arthurdejong looked to be promising. However, as the library is not in typescript, you will most likely need to port the relevant sections of the code over to typescript, after your verification.

**Comment by hui-jie-lim** [comment]
Heyy @KenLSM , I did a round of validation (only for correct UENs, not wrong ones). (See [this](https://github.com/hui-jie-lim/sg_uen_checker/tree/main)). 

Its generally sound but UENs of type UF (unregistered foreign entities) will return an error. I think its fine since these UENs cannot be used to transact with gov agencies but I am not sure if will affect the functionality of FormSG. 

Alternatively, I can surpress the error by adding 'UF' to OTHER_UEN_ENTITY_TYPES

Let me know how the team would like to proceed. Thanks!

Also, just to check - we update here? 
`FormSG/blob/develop/shared/utils/uen-validation.ts`

**Comment by KenLSM** [comment]
Hey @hui-jie-lim, the lib test looks good. Would be better if we can have some test with some failure cases (perhaps 
1) switching the entity types to AA/BB which definitely doesn't exist, and 2) changing the checksum to another character).

> Alternatively, I can surpress the error by adding 'UF' to OTHER_UEN_ENTITY_TYPES

Yeah, that sounds reasonable. Could we also ensure that `BN, LC, VC, EC, HC, FS` are entities also included in others? -- we've previously encountered issues where the companies are legit but our validators failed them.

> we update here?
> `shared/utils/uen-validation.ts`

Yep :)

**Comment by hui-jie-lim** [comment]
Hey @KenLSM , sounds good. I'll work on them. 
Could you assign me the issue please? Thank you

**Comment by KenLSM** [comment]
Hey @hui-jie-lim before I forget, could you help to fill in this [Contributor License Agreement](https://github.com/opengovsg/FormSG/blob/develop/CONTRIBUTING.md#contributor-license-agreement) if you haven't?

**Comment by hui-jie-lim** [comment]
hey yes, i have submitted the CLA form [here](https://go.gov.sg/ogp-cla) :)

**Comment by hui-jie-lim** [comment]
hello @KenLSM , 

- I have updated the checker with unhappy paths. They are mostly just brute force digit checks and org codes checks. Generally speaking, while the stdnum code is pretty robust, it is not able to properly detect some org code changes. Its unlikely to be the fault of stdnum code though. I reckon its more because we are wrapping around a modulus for the digit checks are there are just some unfortunate overlaps when we loop from AA to ZZ.     
``` see https://github.com/hui-jie-lim/sg_uen_checker```

- I am also done with a first cut of the code for the UEN validator but am working on the tests now (having some struggles with docker). I havent been able to test the code but by and large, I have kept it pretty close to the code for stdnum, so should be alright. You can find it here. 
```https://github.com/hui-jie-lim/FormSG/blob/develop/shared/utils/uen-validation.ts```

**Comment by LinHuiqing** [comment]
resolved in https://github.com/opengovsg/FormSG/pull/6534
