### ISSUE TITLE
chore: use handle-mongo-error utility to generate error string for Database error

### ISSUE THREAD

**Issue by tshuli** [opengovsg/FormSG#614]
Extension of #602

**Comment by liangyuanruo** [comment]
Application code is using `new DatabaseError(getMongoErrorMessage(error))`

**Comment by karrui** [comment]
Not all, we should also return database errors with `handle-mongo-error.ts#transformMongoError` instead of `getMongoErrorMessage` too, for better error typings instead of just the message. Most of our code is still returning with 
```ts
return new DatabaseError('some message')
``` 
instead of

```ts
return transformMongoError(error)
```

which can give more specific errors. Probably not a priority though, as we usually do not discriminate between the various database errors.
