### ISSUE TITLE
findLatestSuccessfulPaymentByEmailAndFormId should return most recently completed payment document

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#6204]
**Describe the bug**
`findLatestSuccessfulPaymentByEmailAndFormId` currently returns payment documents that is most recently **created**.

However, what is expected is the latest successful payment that is most recently **completed**.

**To Reproduce**
We will create two incomplete payments using the same email.
1. On a payment form, verify your email and click `Proceed to Pay`.
   Let this form be `FormA`, 
2. On the same payment form, make a new submission, verify your email and click `Proceed to Pay`.
   Let this form be `FormB`
3. On `FormB`, complete the payment.
4. On `FormA`, complete the payment.
5. On the same payment form, make another new submission, verify your email and click `Proceed to Pay`.
  Notice that Previous payment check returns `FormB`.

**Expected behavior**

Expecting Previous payment check to return `FormA` since it is the most recently **completed** payment

**Comment by brycegoh** [comment]
Hello, first time contributing and also just browsed through the code so apologies if I mess up along the way as I pen down my proposed solution and thoughts.

## Proposal
Looking at the description and code, I see that the original `findLatestSuccessfulPaymentByEmailAndFormId` sorts by id in desc order which results in the latest created payment. Since we do store the completed payment data, I propose we could sort it using `completedPayment.paymentDate`?

```js
PaymentModel.findOne({
  email: email,
  formId: formId,
  status: PaymentStatus.Succeeded,
})
  .sort({ 'completedPayment.paymentDate': -1 })
  .exec()
```
Side Note:
I suppose I could also tackle [#6182](https://github.com/opengovsg/FormSG/issues/6182) as well. The following is the proposed solution including the previous example:
```js
ResultAsync.fromPromise(
PaymentModel.findOne({
  email: email,
  formId: formId,
  status: PaymentStatus.Succeeded,
  'completedPayment.paymentDate': {
    $gt: moment().subtract(30, 'days').toDate(),
  },
})
  .sort({ 'completedPayment.paymentDate': -1 })
  .exec(),
```

## Clarifications
- Can I assume when a payment has a `status` of `PaymentStatus.Succeeded`, the `completedPayment` metadata will also be updated?

**Thoughts**
I assumed that `completedPayment` must be non-empty when `status === PaymentStatus.Succeeded`  because the stripe webhook handler calls `confirmStripePaymentPendingSubmission` before updating the payment record `status`.

Therefore, if we assume the stripe event has `charge.succeeded` then,
  1.  In `processStripeEventWithinSession` function, it calls `confirmStripePaymentPendingSubmission` which updates payment record's `completedPayment`.
  2. Then, the `payment` record's status is then updated to `PaymentStatus.Succeeded`.

**Comment by KenLSM** [comment]
Hey @brycegoh thanks for looking at this as well as #6182. I think your proposal makes sense, although we might need to take care of the timezone. I'm not exactly sure if `moment()` will create a date in the local timezone or with `UTC +0`.

Would you want to work on this? I'll assign both tickets to you if that's the case :)

> Can I assume when a payment has a status of PaymentStatus.Succeeded, the completedPayment metadata will also be updated?

Yes, I think that's a fair assumption.

**Comment by brycegoh** [comment]
> Hey @brycegoh thanks for looking at this as well as #6182. I think your proposal makes sense, although we might need to take care of the timezone. I'm not exactly sure if `moment()` will create a date in the local timezone or with `UTC +0`.
> 
> 
> 
> Would you want to work on this? I'll assign both tickets to you if that's the case :)
> 
> 
> 
> > Can I assume when a payment has a status of PaymentStatus.Succeeded, the completedPayment metadata will also be updated?
> 
> 
> 
> Yes, I think that's a fair assumption.

Yes please do assign them to me, I don't mind helping out with both of the issues!

Regarding the timezone, you are right that moment is in local server timezone! Thanks for pointing it out. Will change it to UTC in the implementation.

MomentJS objects are in local timezone by default. Apologies, I had assumed it is similiar to javascript's date object that stores datetime as UTC by default.

**Comment by KenLSM** [comment]
Hey @brycegoh could you help me to leave a comment on #6182 indicating that you would like to look at the issue? -- github didn't register you as a possible assignee, I figured that it might have to do with it

Also could you help to fill in this [Contributor License Agreement](https://github.com/opengovsg/FormSG/blob/develop/CONTRIBUTING.md#contributor-license-agreement) if you haven't?

**Comment by brycegoh** [comment]
> Hey @brycegoh could you help me to leave a comment on #6182 indicating that you would like to look at the issue? -- github didn't register you as a possible assignee, I figured that it might have to do with it
> 
> Also could you help to fill in this [Contributor License Agreement](https://github.com/opengovsg/FormSG/blob/develop/CONTRIBUTING.md#contributor-license-agreement) if you haven't?

Done both. Thanks!
