### ISSUE TITLE
Shard Submission service into separate Encrypted and Email services

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#780]
Storage mode responses and email responses require separate processing. Shard out mode-specific functionality from the existing Submission service into two new separate services for clarity and the avoidance of doubt. 

Blocked by #1104

**Comment by mantariksh** [comment]
if the opportunity arises, we should also use this refactor to avoid modifying the shape of responses after we receive them. for example, for email submissions, we should keep attachments as its own array instead of assigning additional `filename` and `content` keys to attachment responses in the `responses` array (see `addAttachmentsToResponses`). this results in strange behaviour, e.g. we start off with an array of attachments, then distribute the information in it to the attachment responses in the `responses` array, then later on we reconstruct the attachments array that we started with.

**Comment by mantariksh** [comment]
Subsumed by #1104, which will split the mode-specific service functionality into two separate classes
